### ISSUE TITLE
User can set the date of an event

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/template#18]
When a user posts a new event, let them set a date (what day).

We'll add a new text input (the white box you type words into) to _post.html_

### Part 1
- [ ] in post.html, add a new text `<input>` field where the user can write the date. You can copy and paste the input where they write their message.
- (Don't copy the whole form - we're just adding a new input, which is the empty space you write into, to the existing form. There should still only be one 'Post it!' button for the whole form.
- [ ] Give your new `<input>` field has a unique class name, e.g. `class="dateInput"`
- [ ] Check: open localhost:3000/post.html and check your new input field appears on the form.

### Part 1.5

OK instead of typing in a date we want a cool date picker (like a little calendar)

That's too much work to code ourselves so we'll use one that's already been made

We can use jquery-ui, which is an extension to jquery.

- [ ] Add these line to the head of the page:

```html
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
```
In the javascript near the end of your page, use this command to add a date picker to the input field

```javascript
$( ".dateInput" ).datepicker();
```

Replace `dateInput` with the *class* that you put on the input you want the date picker to connect to.

### Part 2

If someone has already finished the issue **Clicking 'Post it!' should not go to a new page** then you need to do an extra step:
- [ ] in post.html, update the javascript so it sends the new form field to the server. (Look at the existing code for reference. You need to add one line of JavaScript code.)
- You will need to add one line to the javascript in post.html. This will be very similar to the line that starts with `data.message =`… but will need to set `data.date` instead.
- If no-one has done **Clicking 'Post it!' should not go to a new page**, you can skip this step.

### Part 3

Now it's (hopefully) being sent to the server, we need to teach the server to look out for this new information.
- [ ] We're now working in _index.js_
- [ ] find for the code that is run when a user POSTS a new post to the server.
- [ ] there is a line that writes the post's message to the console using `console.log(request.body.message);`. Add another line that logs request.body.date as well.
- [ ] Restart the server, post a new post and check that the event date now shows up in terminal/command prompt.
- [ ] If the date is coming through, we can now save it. You do this by setting a new new name-value pair on the `post`. Your code might look like this:

``` javascript
post.date = request.body.date;
```
### Part 4
- [ ] Save some new posts then check how they look in raw form at http://localhost:3000/posts – each post should have a date now.
- [ ] modify feed.html so that each post displays the date (`post.date`). Try copying the code that's already there.

### notes

This task does not include updating the CSS look + feel of the post.html page. Just make it work, don't focus on making it pretty in this ticket.
