### ISSUE TITLE
Clicking 'Post it!' should not go to a new page - must be done first!

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/template#2]
Currently, when you click 'Post it!' on the **post.html** page, you are taken to a new page that says "thanks for your message. Press back to add another"

This is confusing and not very attractive.

After this change, when you click the button,
1. you stay on the same page
2. a little box pops up that says "Thanks! Your message was saved!"

All these changes are in post.html

## Part 1

You will need to include jQuery in the page (if it is not already included). You do this by adding **one line** of HTML code to the HEAD of the page. Look in the `<head>` of the feed.html for the line you need to copy.

jQuery is a library (a whole lot of javascript code that someone else wrote so we don't have to).

- [ ] Add jQuery to **post.html** by copying the line from **feed.html** into **post.html**

In **post.html**, use jQuery to make something happen when you click the 'Post it!' button:
- [ ] in the html, add a class to the `<button>` so we can find it using javascript - it should end up looking like `<button class="postButton">`
- [ ] add a pair of `<script>` tags so we can add some javascript between them. Add these near the end of the file, just above `</body>` and `</html>`
- [ ] in your script, add this function:

``` javascript
var myCoolFunction = function (e) {
    e.preventDefault();
    alert("nothing happens - except this alert!");
}
```

Now we must tell the button to run the function when you click on it. This is similar to what we did in the fivestar and tvshow activities

- [ ] add this line to your javascript:

``` javascript
$(".postButton").on("click", myCoolFunction);
```

**PROTIP**: You must define your function must _before_ (i.e. above) where you use it. Your `on("click"` command must come after you explain what your cool function is, otherwise it won't know what you're talking about when you refer to `myCoolFunction`.

_What is this doing?_
* We told the button to call the function when you click on it
* Inside the function, `e.preventDefault()` turns off the browser's built in action (which was to send data to our server AND go to a new page).
* The `alert` command is just there to show your code is working. We will delete it later because it's super annoying.
- [ ] TEST: clicking 'Post it!' should now make an annoying message pop up! But it does NOT add anything to the message feed any more. yay :/

## Part 2

history lesson (you can skip this):

> Before your change, this page works using an old-school technique from before JavaScript was a thing. In the HTML is a form. A form is just like a paper form - you fill it in. When you press the button, your browser takes all the things you wrote, puts them together into a message, and POSTs it to the address specified at the top of the form. Then your browser waits for the response from the server. When it arrives, it displays the response ("Thanks for your message…").

In your new function, we now need to do the same thing but write it ourselves: make it do a POST that sends the right info to the server.

You could look up "how to POST using jQuery" on google and find some examples, but to save you time I've pulled a good example out here:

``` javascript
var data = {};
$.post( "url" , data );
```
- [ ] add that code **inside** your cool function.
- [ ] Change the first argument from "url" to "/posts" - this is where we are posting to. (It has to match the address the server is listening to in index.js)
- [ ] TEST: clicking the button should now add a new message to the message feed - but it will be `null`, instead of what you typed in.
- [ ] delete that annoying `alert` command.
### Part 3

How do we get the words the user typed in, and send them to the server?

We will use jQuery to get the part of the HTML page the user is typing into.
Just like the button, we need to give this part of the HTML a class so our javascript can select it.
- [ ] Add a _class_ to the `<input>` where your message goes. i.e. `class="messageInput"`

Now we can select it with jQuery, and get the value out of it using the `.val()` function.

``` javascript
data.message = $(".messageInput").val();
```

You'll need to add the line above just after the line `var data = {}`. That means, after we create an empty object named 'data', but before we send the object to the server, we add some information to it.
- [ ] Test: Make a post. The post should correctly appear in the feed.

### Part 4: show feedback
- [ ] Add an empty div to the page (inside the `body`) with a class 'note' i.e. `<div class="note"></div>`
- [ ] In your cool function, tell jquery to select that div and change the text inside it to say "Thanks! Your message was saved!" using some code like this: `$(".note").text("Thanks! Your message was saved!");`

- [ ] TEST: when you post, the page shows some feedback to let you know it saved your post.
- [ ] TEST: the page doesn't show the feedback until you post something.
